/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code_wizard.gui;

import code_wizard.dao.OrderDao;
import code_wizard.dao.ProductDao;
import code_wizard.pojo.ProductPojo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class BillingFrame extends javax.swing.JFrame {
    ArrayList <ProductPojo> al=new ArrayList<>();
    DefaultTableModel tm;
    double total=0.0;
    double grtotal=0;
    public BillingFrame() {
        initComponents();
      this.setLocationRelativeTo(this);
        tm=(DefaultTableModel)jtproducts.getModel();
        productidtxt.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productid = new javax.swing.JLabel();
        productidtxt = new javax.swing.JTextField();
        bckbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtproducts = new javax.swing.JTable();
        generatebillbtn = new javax.swing.JButton();
        lblSum = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("    Billing Frame");

        productid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productid.setText("Product id");

        productidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productidtxtActionPerformed(evt);
            }
        });

        bckbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bckbtn.setText("Back");
        bckbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckbtnActionPerformed(evt);
            }
        });

        logoutbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutbtn.setText("Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        jtproducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Product Name", "Product Price", "Our Price", "Product company", "Quantity", "Tax", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtproducts);

        generatebillbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        generatebillbtn.setText("Generate Bill");
        generatebillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebillbtnActionPerformed(evt);
            }
        });

        lblSum.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSum.setText("0");

        Total.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Total.setText("Total :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(productid, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addComponent(bckbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(generatebillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(Total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(286, 286, 286))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bckbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generatebillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 46, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void productidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productidtxtActionPerformed
        if(productidtxt.getText().trim().isEmpty()){
           // JOptionPane.showMessageDialog("please enter product id","error",JOptionPane.ERROR_MESSAGE);
       JOptionPane.showMessageDialog(null,"Please enter Product id", "Error" ,JOptionPane.ERROR_MESSAGE);
        return;
        }
        loadItemList(productidtxt.getText().trim());
        lblSum.setText(String.valueOf(Total));
        generatebillbtn.setEnabled(true);
    }//GEN-LAST:event_productidtxtActionPerformed

    private void generatebillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatebillbtnActionPerformed
     // tm=(DefaultTableModel)jtAllStocks.getModel();
        try{
           String ordid=OrderDao.getNextOrderId();
            System.out.println(ordid);
           if(OrderDao.addOrder(al,ordid) && ProductDao.updateProducts(al))
           JOptionPane.showMessageDialog(null,"Orders of Rs."+total+"/- created","Success", JOptionPane.INFORMATION_MESSAGE);
            int a=JOptionPane.showConfirmDialog(null, "Are you want to proceed");
            if(a==0)
           {
               JOptionPane.showMessageDialog(null, "Order of RS"+grtotal+"/- OrderCreated Succesfully");
               ViewOrdersFrame vorder=new ViewOrdersFrame();
                vorder.setVisible(true);
                this.dispose(); 
           }   //clear.jtproducts();
       }catch(Exception e) 
       {
        e .printStackTrace(); // Print the SQL exception details
       } 
    }//GEN-LAST:event_generatebillbtnActionPerformed

    private void bckbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckbtnActionPerformed
       ReceptionistOptionFrame eframe=new ReceptionistOptionFrame();
        eframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bckbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        LoginFrame lframe=new LoginFrame();
        lframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Total;
    private javax.swing.JButton bckbtn;
    private javax.swing.JButton generatebillbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtproducts;
    private javax.swing.JLabel lblSum;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JLabel productid;
    private javax.swing.JTextField productidtxt;
    // End of variables declaration//GEN-END:variables

    private void loadItemList(String pid) {
       try
       {
           ProductPojo p=ProductDao.getProductById(productidtxt.getText().toString().trim());
           if(p.getProductid()==null){
            JOptionPane.showMessageDialog(null,"Please enter Product id", "Error" ,JOptionPane.ERROR_MESSAGE);
            return;
        }  
           int index=getproductid(pid);
           if(index==-1)
           {
               Object[]rows=new Object[8];
               int quan=1;
               double amt=quan*p.getOurprice();
               p.setQuantity(quan);
               p.setTotal(amt+(amt*p.getTax()/100));
               rows[0]=p.getProductid();
               rows[1]=p.getProductname();
               rows[2]=p.getProductprice();
               rows[3]=p.getOurprice();
               rows[4]=p.getProductcompanyname();
               rows[5]=p.getQuantity();
               rows[6]=p.getTax();
               rows[7]=p.getTotal();
               tm.addRow(rows);
               al.add(p);
               grtotal+=p.getTotal();
           }
           else
           {
               ProductPojo prd=al.get(index);
               int oldq=(int)tm.getValueAt(index,6);
               double amt=prd.getOurprice();
              float tax=prd.getTax();
               amt=amt+(amt*tax/100);
                total=(double)tm.getValueAt(index, 8);
               tm.setValueAt(++oldq,index ,6);
               tm.setValueAt(total+amt, index,8);
               grtotal+=amt;
               prd.setQuantity(oldq);
               prd.setTotal(total+amt);
               al.set(index, prd);
           }
           }
       
       catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Problem In The Database!!", "Error!!", JOptionPane.ERROR_MESSAGE);
            System.out.println("SQLException is "+ex);
            ex.printStackTrace();
        }
    }
    private int getproductid(String pid)
    {
        int index=-1;
        for(int i=0;i<al.size();i++)
        {
            ProductPojo p=al.get(i);
            if(p.getProductid().equals(pid))
            {
                index=i;
                break;
            }
        }
        return 0;
    }
}
